version: '3'

services:
  mongodb:
    build: ./mongo
    image: 'finup-mongo:1.0.0'
    restart: unless-stopped
    volumes:
      - ./mongo/mongo_data:/data/db
    networks:
      - dev-net
    ports:
      - '27017:27017'
  auth-backend:
    depends_on:
      - mongodb
    build: ./b-auth
    image: 'finup-b-auth:1.0.0'
    restart: unless-stopped
    env_file:
      - ./env/db.env
      - ./env/jwt-secret.env
    environment:
      - APP_PORT=8081
    networks:
      - dev-net
    ports:
      - '8081:8081'
  user-backend:
    depends_on:
      - mongodb
    build: ./b-user
    image: 'finup-b-user:1.0.0'
    restart: unless-stopped
    env_file:
      - ./env/db.env
      - ./env/jwt-secret.env
    environment:
      - APP_PORT=8080
    networks:
      - dev-net
    ports:
      - '8080:8080'

networks:
  dev-net: